sudo: false
language: node_js
script:
  - if [[ $(node --version) = v8.* ]]; then make deps && make dist; fi
  - if [[ $(node --version) = v6.* ]]; then make -C fluent-syntax dist; fi
  - make -C fluent-syntax test-without-babel-polyfill
node_js:
  - "6"
  - "8"
cache:
  directories: node_modules
notifications:
  irc:
    channels:
      - "irc.mozilla.org#l20n"
    on_success: always
    on_failure: always
    use_notice: true
    template:
      - "#%{build_number} %{message} %{build_url}"
      - "Change by %{author}: %{compare_url}"
